Sleeping beauty
commitglobal/ptsd-help-mobile pull request #24
Opened 2024-12-05 12:41 UTC by dragos1195

2024-12-05 12:45 UTC, luciatugui commented on app/(app)/tools/sleep/_layout.tsx
> +      <Stack.Screen name='sleep-habits/index' options={{ headerShown: false }} />
le poti face direct fisiere aceste rute, no need for extra folders

2024-12-05 12:54 UTC, luciatugui commented on app/(app)/tools/sleep/sleep-habits/index.tsx
> +  const items = [
maybe memo this?

2024-12-05 12:56 UTC, luciatugui commented on app/(app)/tools/sleep/sleep-habits/no-sleep-activities/index.tsx
> +      <Stack.Screen options={{ headerShown: false }} />
daca alegi sa refaci layout-ul fara foldere, o sa poti sterge asta din componenta.

2024-12-05 13:14 UTC, luciatugui commented on components/StarList.tsx
> +        contentContainerStyle={{ padding: 16, paddingBottom: 16 }}
aici padding-ul nu-i acelasi lucru? sau voiai sa pui si insets jos?

2024-12-06 09:27 UTC, radulescuandrew commented on app/(app)/tools/sleep/sleep-habits/awake-activities.tsx
> +  const activities = useMemo(() => {
Ma asteptam sa vad aici maparea cu favorite true/false si mi-a luat ceva sa ma uit in StarList.

2024-12-06 09:36 UTC, radulescuandrew commented on components/StarList.tsx
> +    setIsReminderChecked(sleepActivity?.notificationId !== null);
Asta o sa dea true, pentru ca `undefined !== null`

2024-12-06 09:58 UTC, radulescuandrew commented on components/StarList.tsx
> +  const items = useMemo(
Putem sa facem asta in componenta parinte si acolo tragem si din DB

2024-12-06 09:58 UTC, radulescuandrew commented on components/StarList.tsx
> +  const [, setFavoriteItems] = useState<string[]>([]);
Nu cred ca avem nevoie de state-ul asta

2024-12-06 10:00 UTC, radulescuandrew requested changes
dasdsa

2024-12-06 10:00 UTC, radulescuandrew commented on components/StarList.tsx
> +            {hasReminder && (
De ce nu o tinem in parinte?

2024-12-06 12:10 UTC, merged